var userInfo = [
{
  "login": "raveve",
  "id": 8239281,
  "avatar_url": "https://avatars.githubusercontent.com/u/8239281?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/raveve",
  "html_url": "https://github.com/raveve",
  "followers_url": "https://api.github.com/users/raveve/followers",
  "following_url": "https://api.github.com/users/raveve/following{/other_user}",
  "gists_url": "https://api.github.com/users/raveve/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/raveve/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/raveve/subscriptions",
  "organizations_url": "https://api.github.com/users/raveve/orgs",
  "repos_url": "https://api.github.com/users/raveve/repos",
  "events_url": "https://api.github.com/users/raveve/events{/privacy}",
  "received_events_url": "https://api.github.com/users/raveve/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Raven Askew",
  "company": "",
  "blog": "http://ravenaskew.com",
  "location": "Charleston, SC",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 9,
  "following": 12,
  "created_at": "2014-07-22T20:40:23Z",
  "updated_at": "2015-01-26T21:51:44Z"
}
];
